sudo: required
services:
        - docker

before_install:
        - docker build -t shoyooyo/project3test -f ./client/Dockerfile.dev ./client

script:
        - docker build -t shoyooyo/project3
after_success:
        - docker build -t shoyooyo/project3prod -f ./client
        - docker build -t shoyooyo/project3nginx -f ./nginx
        - docker build -t shoyooyo/project3server -f ./server
        - docker build -t shoyooyo/project3worker -f ./worker

