sudo: required
services:
        - docker

before_install:
        - docker build -t shoyooyo/project3test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true shoyooyo/project3test npm test

          #script:
          #        - docker build -t shoyooyo/project3
after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker build -t "$DOCKER_ID"/project3prod ./client
        - docker build -t "$DOCKER_ID"/project3nginx ./nginx
        - docker build -t "$DOCKER_ID"/project3server ./server
        - docker build -t "$DOCKER_ID"/project3worker ./worker
          # code to login to docker
          #        - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
          #        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          # code to push docker image
        - docker push "$DOCKER_ID"/project3prod
        - docker push "$DOCKER_ID"/project3nginx
        - docker push "$DOCKER_ID"/project3server
        - docker push "$DOCKER_ID"/project3worker
